### ISSUE TITLE
file encoding problems

### ISSUE THREAD

**Issue by selmf** [josetesan/yacreaderlibrary-server-docker#2]
Some users are [reporting](http://www.yacreader.com/forum/support-linux/1124-server-will-not-import-comics-w-special-chacters
) troubles with german and french unicode characters and this docker container.

As I'm not having any of these troubles I suspect that this is actually a locale problem. Could you add a locale to the docker container? Preferably UTF-8.

[Here](http://jaredmarkell.com/docker-and-locales/) are some hints how it could be done.

**Comment by josetesan** [comment]
Sure , I’ll release a new version later today
I’ll be based on 9.0

Descarga Outlook para iOS<https://aka.ms/o0ukef>
________________________________

**Comment by selmf** [comment]
You might want to wait until Luis merges this pull request into the default branch:

https://bitbucket.org/luisangelsm/yacreader/pull-requests/64/901-fixes/diff#comment-None

It contains some fixes that are needed to build on Debian.

**Comment by selmf** [comment]
Ok, it's included.

**Comment by josetesan** [comment]
I’ve just build a new image , please try it

Descarga Outlook para iOS<https://aka.ms/o0ukef>
________________________________

**Comment by selmf** [comment]
There is something strange going on. I can't pull the image, the Docker hub repo has no tags and the last push is set to "never".

**Comment by josetesan** [comment]
Please check latest version, its based on 9.5.0
