### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by partymike** [josetesan/yacreaderlibrary-server-docker#4]
I notice you've updated to the latest version here but on the docker hub it shows as last updated 4mths ago...does the container self update on start?

I use watchtower to handle all my docker updates and noticed yours wasn't getting pulled.

**Comment by josetesan** [comment]
Latest version , 9.5.0 has migrated from mercurial to git and I haven’t tested the guild process yet. In a couple of days I’ll release a new version with it. I did push the dockerfile but not sure if the hook did work

Descarga Outlook para iOS<https://aka.ms/o0ukef>
________________________________

**Comment by partymike** [comment]
seem to have worked as new version showing on hub and pulled ok, cheers for that :-)
